name: Autograding Tests

on:
  push:
  workflow_dispatch:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hello World Test
        id: hellotest  # ID with no hyphen
        uses: classroom-resources/autograding-io-grader@v1
        with:
          test-name: Hello World Output
          id: hellotest
          command: python3 hello.py
          expected-output: Hello, Python World!
          comparison-method: substring
          timeout: 10

      - name: Report Autograding Results
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners:
            - hellotest