
     name: GitHub Classroom Workflow
     on: [push]
     jobs:
       build:
         name: Autograding
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v4
             with:
               fetch-depth: 1
           - name: Set up Python
             uses: actions/setup-python@v5
             with:
               python-version: '3.x'
           - name: Check if hello.py exists
             run: |
               if [ ! -f hello.py ]; then
                 echo "::error::hello.py not found in the repository root. Please submit a file named 'hello.py'."
                 exit 1
               fi
             working-directory: ./
           - uses: education/autograding@v1
  
